import "../styles/tailwind.css";
import React from "react";
import Layout from "../components/Layout/Layout";

export const metadata = {
    title: "Web tutorials",
    description: "Generated by Yerim",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html>
            <body>
                <Layout>{children}</Layout>
            </body>
        </html>
    );
};

export default RootLayout;
